DiyConnect/DiyConnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
urlpatterns = [
    path('admin/', admin.site.urls),
   path("", include("main.urls"))
   
]
handler404  = "main.views.custom_404_view"
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DiyConnect/main/urls.py
from django.urls import path,include

from .  import views

app_name ="main"
urlpatterns = [
    path('', views.index, name="index" ),
    path('authentication_base/', views.authentication_base, name="authentication_base" ),
    path('authentication/login/', views.authentication_login, name="authentication_login" ),
    path('authentication/registration/', views.authentication_registration, name="authentication_registration" ),
    path('authentication/profile/', views.authentication_profile, name="authentication_profile"),
     path('authentication/PreLoad/', views.authentication_preLoad, name="authentication_preLoad"),
          path('authentication/forgot-password/', views.authentication_forgot_password, name="authentication_forgot_password"),
           path('authentication/changepassword/', views.changeNewpassword, name="changeNewpassword"),

     # CRUD OPERATION AUTHENTICATION
    path('authentication/ADD/', views.authentication_ADD, name="authentication_ADD"),
    path('authentication/logout/', views.authentication_logout, name ="authentication_logout"),

    # DIY CONNECT APP
    path('diyconnect/home/', views.home,  name="diyconn_home"),
    
    #People
 path('diyconnect/people/', views.people,  name="people"),
 path('diyconnect/people/friends', views.peopleFriends,  name="peopleFriends"),
 path('diyconnect/people/discover', views.peopleGetDiscover, name ='peopleGetDiscover'),
 path('diyconnect/people/friendRequest', views.peopleFriendRequest_get, name ='peopleFriendRequest_get'),
 path('diyconnect/people/friendRequest/accepted/<int:user_id>', views.peopleFriendRequest_accepted, name ='peopleFriendRequest_accepted'),
  path('diyconnect/people/friendRequest/pending/<int:user_id>', views.peopleFriendRequest_pending, name ='peopleFriendRequest_pending'),
 path('diyconnect/people/add/<int:user_id>', views.peopleAdd, name ='peopleAdd'),
 path('diyconnect/people/delete/<int:user_id>', views.peopleDelete, name ='peopleDelete'),
 
 
    #Search
    path('diyconnect/search/<str:search_item>', views.postSearch,  name="postSearch"),

    #POST
      path('post/getRoleChange/', views.postRoleChange,  name="postRoleChange"),
      path('post/add/', views.postAdd,  name="postAdd"),
            path('post/specific/<int:post_id>', views.postGet_specific,  name="postGet_specific"),   #FINALIZED
      path('post/edit/save/<int:post_id>', views.postEditSave,  name="postEditSave"),
      path('post/edit/<int:post_id>', views.postEdit,  name="postEdit"),
      path('post/get/<int:lastest_post>/<str:role_post>', views.postGet,  name="postGet"),
        path('post/delete/<int:post_id>/', views.postDelete,  name="postGet"),

      path('post/profile/get/<str:username>/', views.postGet_profile, name="postGet_profile"),

      #POST LIKE
       path('post/like/add/', views.postLikeAdd, name="postLikeAdd"),
         path('post/like/removed/', views.postLikeRemoved, name="postLikeRemoved"),

    #Conversations
        path('diyconn/conversation/get/<int:sender_id>', views.MessageConversationGet,  name="MessageConversationGet"),
          path('diyconn/conversation/add/<int:receiver_id>', views.MessageConvesationAdd,  name="MessageConvesationAdd"),
    #Messages
 path('diyconn/messages/mobile', views.MessageMobile,  name="MessageMobile"),
  path('diyconn/messages/mobile/get/<int:user_id>', views.MessageMobileConversationContent,  name="MessageMobileConversationContent"),
  path('diyconn/messages/', views.Messages,  name="Messages"),
  path('diyconn/messages/get', views.MessagesGet,  name="MessagesGet"),
  path('diyconn/messages/add/<int:receiver_id>', views.MessageAdd,  name="MessageAdd"),
  path('diyconn/messages/request/add/<int:receiver_id>', views.MessageAddRequest,  name="MessageAdd"),

  #Profile
    path('diyconn/profile/get/<str:username>/', views.profile_user, name ="profile_user"),
  #Request Task
    path('diyconn/request/fullfiller/cancelled/', views.request_fulfiller_cancelled, name ="request_fulfiller_cancelled"),
       path('diyconn/request/receiver/completed/', views.request_receiver_completed, name ="request_receiver_completed"),

      #INITIALIZED
        path('Initialized/cookies/', views.set_csrf_token,  name="set_csrf_token"),
  
  #Reviews
   path('diyconn/reviews/<int:user_id>', views.reviews,  name="reviews"),


#Notification 
 path('diyconn/notification/', views.notification,  name="notification"),
  path('diyconn/notification/viewed/<int:notif_id>', views.notification_viewed,  name="notification_viewed"),
   #Setting
   path('diyconn/setting/', views.setting,  name="setting"),
    path('diyconn/setting/verify-password', views.setting_verify_password,  name="setting_verify_password"),
     path('diyconn/setting/save-changes', views.setting_save_changes,  name="setting_save_changes"),
 
 #feedback 
    path('diyconn/feedback/add', views.user_feedback,  name="user_feedback"),

 #admin
     path('diyconn/admin-fogotPassword/', views.admin_forgotPassword,  name="admin_forgotPassword"),
     path('diyconn/admin-dashboard/', views.admin_dashboard,  name="admin_dashboard"),
     path('diyconn/admin-checkUserpost/', views.admin_CheckUsers,  name="admin_CheckUsers"),
  path('diyconn/admin-checkUserpostDetails/', views.admin_checkUserpostDetails,  name="admin_checkUserpostDetails"),
    path('diyconn/admin-postDelete/<int:post_id>', views.admin_deletePostDetails,  name="admin_deletePostDetails"),
      path('diyconn/admin-feedback/', views.admin_feedbackCheck,  name="admin_feedbackCheck"),
    path('diyconn/admin-UserDelete/<int:user_id>', views.admin_deleteUser,  name="admin_deleteUser"),


     

]

DiyConnect/main/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
from django.contrib.auth.hashers import check_password
from .models import UserSites, UserPost, UserPost_BLOB, Friendships, UserMessages, MessageStatus,TaskRequest,Review,PostLike,FriendStatus, Notification, NotifyType,NotifyStatus, FogotPasswordFixed,Feedback
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required, user_passes_test
import time
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models.functions import Random
from django.db.models import Q, Max, OuterRef, Subquery, F,Case, When,Exists
from django.db import models
import random
import string

# Create your views here.


#initialized_cookie
@ensure_csrf_cookie
def set_csrf_token(request):
    return JsonResponse({"message": "CSRF token set"})


def index(request):
    context ={}
    return render(request, 'main/index.html', context)



# Authentication
def authentication_base(request):

    context ={}
    return render(request,'main/authentication/auth_base.html',context)

def authentication_login(request):
    if(request.method =="POST"):
        data = json.loads(request.body)    
        try:
            u_check = UserSites.objects.filter(username=data['username']).first()
           
            """
            print("Input Password:", data['password'])
            print("Stored Hashed Password:", u_check.password)
            print(data)
            print(u_check.password)
            print(check_password(data['password'], u_check.password))
            """
            if(check_password(data['password'], u_check.password)):
                user = authenticate(request, username=data['username'], password=data['password'])
                login(request, user)  # Log the user in
                request.session["RolesPostFilter"] = 'Innovator'
                return JsonResponse({"msg": "User has been retrieve", "redirect_url": "/diyconnect/home/"}, status=200)
            else:
                return JsonResponse({"error": "Invalid username or password."}, status=400)
        except:   
             return JsonResponse({"error": "Invalid username or password"}, status=400)
    context ={}
    return render(request,'main/authentication/auth_login.html',context)


def authentication_registration(request):
    context ={}
    return render(request,'main/authentication/auth_registration.html', context)

def authentication_forgot_password(request):
    context={
        
    }
    return render(request,'main/authentication/auth_forgot_pass.html', context)

def authentication_preLoad(request):
    if request.method =="POST":
        data = json.loads(request.body)        
        u_check = UserSites.objects.filter(username = data['username']).exists()
        if(u_check):
            return JsonResponse({"error": "The username has been used."}, status=400)        
        request.session["Pre_User_Profile"] = data
        return JsonResponse({"Profile": "Request Sent", "redirect_url": "/authentication/profile/" }, status=200)    
    return JsonResponse({"error": "Invalid request"}, status=400)
    
def authentication_profile(request):
    user_data = request.session.get("Pre_User_Profile", {})
    context ={
        "UserPreData": user_data
    }
    return render(request,'main/authentication/auth_registrationProfile.html', context)

def authentication_ADD(request):
    if(request.method =="POST"):
        get_image_file = request.FILES.get("ImageFile")
        bio = request.POST.get("bio")
        get_user_data = json.loads(request.POST.get('UserDataPrep'))
        u = UserSites()
        #lastID = UserSites.objects.values('ID').last()
        #u.ID = lastID['ID'] + 1
        u.first_name = get_user_data['firstName']
        u.last_name = get_user_data['lastName']
        u.email = get_user_data['email']
        u.password = get_user_data['password']
        u.profile_picture = get_image_file
        u.city_or_municipality = get_user_data['municipality_or_city']
        u.username = get_user_data['username']
        u.subdivision = get_user_data['subdivision']
        u.bio = bio
        u.save()           
        # Check if data pass server
        """        
        print(get_image_file)
        print(get_user_data)
        print(bio)
        """
        
        return JsonResponse({"msg": "New user created complete."
        ""}, status=200)

    return JsonResponse({"error": "Invalid request"}, status=400)

def authentication_logout(request):
    logout(request)
    return redirect("/authentication/login/")

# DIY CONNECT APP

def home(request):
   
    get_role_post_filter = request.session.get("RolesPostFilter", "Innovator")
    if request.user.is_authenticated:
        get_username = request.user.username
    else:
        get_username = "guest"
    context ={"username": get_username,"role_post_filter":get_role_post_filter}
    return render(request,'main/diyconn/home.html', context)

# POST
@login_required
def postLikeAdd(request):
    if(request.method =="POST"):
        data = json.loads(request.body)
        print(data)
        get_userPost= UserPost.objects.get(ID=data['post_id'])
        p = PostLike()
        p.user =request.user
        p.post = get_userPost
        p.save()
        
       
        
        return JsonResponse({"msg": "Liked Post"}, status=200)
        

@login_required
def postLikeRemoved(request):
    data = json.loads(request.body)
    print(data)
    get_userPost= UserPost.objects.get(ID=data['post_id'])
    get_likePost = PostLike.objects.get(post = get_userPost, user =request.user)
    get_likePost.delete()
    print("removed liked")
    return JsonResponse({"msg": "Liked Post"}, status=200)
def postGet_specific(request,post_id):
     post = UserPost.objects.filter(ID=post_id).first()
     get_post_blobs = UserPost_BLOB.objects.filter(USER_POST_ID=post)
     #print(get_post_blobs)
     if post is None:
         post = False
     context={"post_data":post,
              "post_data_blob":get_post_blobs,
              }
     return render(request,'main/subpages/post/postRetrieve.html', context)


def postGet_profile(request, username):
   
    check_owner_user = False
    user_profile = UserSites.objects.get(username=username)
    user_list_post = UserPost.objects.filter(USER_ID = user_profile).order_by('-modified_at')
    if(request.user==user_profile):
        check_owner_user =True
    context = []
    for post in user_list_post:
            blobs = UserPost_BLOB.objects.filter(USER_POST_ID=post).order_by('position')
            blob_list = [
                {
                    "id": blob.ID,
                    "image_url": blob.blob.url,
                    "position": blob.position
                }
                for blob in blobs
            ]

            context.append({
                "id": post.ID,
                "username":post.USER_ID.username,
                "user_location":{"subdivision": post.USER_ID.subdivision,"city_or_municipality":post.USER_ID.city_or_municipality},
                "title": post.title, 
                "description": post.description,  
                "date_modified": post.modified_at,
                "blobs": blob_list,
                "user_ID":post.USER_ID.ID,
                "check_owner_user":check_owner_user               
            })

    
    
    return JsonResponse({"msg": "Checking if there is a post", "items":context}, status=200)


def postRoleChange(request):
    if(request.method =="POST"):
        data = json.loads(request.body)
        request.session["RolesPostFilter"] = data['role']
      
        return JsonResponse({"msg": "Changing Item Post"}, status=200)


def postGet(request,lastest_post, role_post):
    timeout = 30
    start_time = time.time()
    # = UserPost.objects.filter(user_role_type = role_post )
   
    while time.time() - start_time < timeout:
            try:
                new_posts = UserPost.objects.filter(user_role_type=role_post).order_by("-modified_at")[lastest_post]

                if new_posts:
                    total_likes =0
                    lastest_post +=1  # Update latest post ID
                    get_blob_info  = UserPost_BLOB.objects.filter(USER_POST_ID = new_posts).order_by('position')
                    item = get_blob_info.first().blob.url
                    print(request)
                    get_likes_filter = PostLike.objects.filter(post =new_posts)
                  
                    if request.user.is_authenticated:
                        already_liked = PostLike.objects.filter(post=new_posts, user=request.user).exists()
                       
                    else:
                        already_liked = "guest"
                    for like in get_likes_filter:
                        total_likes+=1
                    return JsonResponse({
                'new_posts':{
                    'id': new_posts.ID,
                    'title': new_posts.title,
                    'description':new_posts.description,
                    'date_modified': new_posts.modified_at,
                    'user': new_posts.USER_ID.ID, 
                    'username': new_posts.USER_ID.username,
                    'user_location':{'subdivision':new_posts.USER_ID.subdivision, 'city_or_municipality': new_posts.USER_ID.city_or_municipality}, 
                    'profile_urls': new_posts.USER_ID.profile_picture.url if new_posts.USER_ID.profile_picture else None,

                    'blob_url': [item.blob.url for item in get_blob_info],
                    "role_post":role_post,
                    "like": total_likes,
                    "already_liked":already_liked,
                   "ownership_post": new_posts.USER_ID == request.user

                  
                    
                    
                },  # Convert queryset to list
                'latest_post_count': lastest_post
            })
         

DiyConnect/main/templates/main/admin_temp/admin_checkUsers.html
{% extends './admin_temp.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Admin | Check Users</title>
    {% endblock title %}
  </head>
  <body>
    <!-- prettier-ignore -->
    {% block content %}
    <!-- //prettier-ignore -->
    <a href="{% url 'main:admin_dashboard' %}" class="button is-info">Home</a>
    <div>User Details</div>
    <div class="columns">
      <div class="column has-text-centered">
        <h1>#</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Username</h1>
      </div>
      <div class="column has-text-centered">
        <h1>First & Last Name</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Email</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Date Created</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Last Login</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Actions</h1>
      </div>
    </div>

    {% for user in users %}

    <div class="columns">
      <div class="column has-text-centered">
        <h1>{{ forloop.counter }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user.username }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user.email }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user.date_created }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user.last_login }}</h1>
      </div>
      <div class="column has-text-centered">
        <div
          class="button has-background-danger"
          onclick="btn_openDelete_user_mdl(event)"
          userdata-username="{{ user.username }}"
          userdata-id="{{ user.ID }}"
        >
          Delete
        </div>
      </div>
    </div>
    {% endfor %}

    <div class="modal" id="mdl_delete_user_post">
      <div class="modal-background" onclick="btn_closeDelete_user_mdl()"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title has-text-centered">Delete User</p>
          <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
          <!-- Content ... -->
          <div id="mdl_txt_content_user"></div>
        </section>
        <footer class="modal-card-foot">
          <div class="buttons">
            <button
              class="button is-success"
              id="btn_mdl_submit_delete"
              onclick="btn_submit_delete_user(event)"
            >
              Save changes
            </button>
            <button class="button" onclick="btn_closeDelete_user_mdl()">
              Cancel
            </button>
          </div>
        </footer>
      </div>
    </div>
    <!-- prettier-ignore -->
    {% endblock content %}
    <!-- //prettier-ignore -->

    <script>
      //{% block scripts %}e
      let mdl_txt_content_user = document.getElementById(
        "mdl_txt_content_user"
      );
      let mdl_delete_user_post = document.getElementById(
        "mdl_delete_user_post"
      );
      let btn_mdl_submit_delete = document.getElementById(
        "btn_mdl_submit_delete"
      );
      function btn_openDelete_user_mdl(event) {
        let target = event.currentTarget;
        let get_username = target.getAttribute("userdata-username");
        let get_user_id = target.getAttribute("userdata-id");
        mdl_txt_content_user.textContent = `Do you want to delete the User: ${get_username}`;
        mdl_delete_user_post.classList.add("is-active");

        btn_mdl_submit_delete.setAttribute("user-id", `${get_user_id}`);
      }
      function btn_closeDelete_user_mdl() {
        mdl_delete_user_post.classList.remove("is-active");
        mdl_txt_content_user.textContent = ``;
        btn_mdl_submit_delete.setAttribute("user-id", ``);
      }

      function btn_submit_delete_user(event) {
        let target = event.currentTarget;
        let user_id = target.getAttribute("user-id");

        let response = fetch(`/diyconn/admin-UserDelete/${user_id}`, {
          method: "POST",
          headers: {
            "X-CSRFToken": getCookie("csrftoken"),
          },
          mode: "same-origin",
        })
          .then((response) => {
            if (!response.ok) {
              // If response status is not OK (400, 500, etc.), throw an error
              return response.json().then((errData) => {
                throw errData;
              });
            }
            return response.json(); // Otherwise, parse the JSON response
          })
          .then((msg) => {
            window.location.reload();
            console.log(msg);
          })
          .catch((err) => {
            //console.log(err);
            console.log("Error:", err.error || "An unexpected error occurred");
            let err_msg = document.getElementById("err_msg");
            err_msg.textContent = `${err.error}`;
          });
      }
      console.log("this for admin check users");
      //{% endblock scripts %}
    </script>
  </body>
</html>

DiyConnect/main/templates/main/admin_temp/admin_dashboard.html
{% extends './admin_temp.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Admin | Dashboard</title>
    {% endblock title %}
    <style>
      /*{% block styles %}*/

      .header-admin {
        font-size: 64px;
        color: black;
      }
      /*{% endblock styles %}*/
    </style>
  </head>
  <body>
    <!-- prettier-ignore -->
    {% block content %}
    <h1 class="header-admin">Admin Dashboard</h1>
    <!-- //prettier-ignore -->
    <a href="{% url 'main:admin_forgotPassword' %}">Forgot Password</a>
    <br />
    <a href="{% url 'main:admin_checkUserpostDetails' %}">Post Details</a>
    <br />
    <a href="{% url 'main:admin_CheckUsers' %}">Users Check</a>
    <br />
    <a href="{% url 'main:admin_feedbackCheck' %}">Feedbacks</a>
    <!-- prettier-ignore -->
    {% endblock content %}
    <!-- //prettier-ignore -->
  </body>
</html>

DiyConnect/main/templates/main/admin_temp/admin_feedback_check.html
{% extends './admin_temp.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Admin | Feedback Check</title>
    {% endblock title %}
  </head>
  <body>
    <!-- prettier-ignore -->
    {% block content %}
    <a href="{% url 'main:admin_dashboard' %}" class="button is-info">Home</a>
    <!-- //prettier-ignore -->
    <h1 class="mb-5">This show people feedback</h1>

    <div class="columns border-admin is-vcentered">
      <div class="column has-text-centered">
        <h1>#</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Username:</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Created At:</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Feedback:</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Rating:</h1>
      </div>
    </div>

    {% for feedback in feedbacks %}
    <div class="columns border-admin is-vcentered">
      <div class="column has-text-centered">
        <h1>{{ forloop.counter }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ feedback.username }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ feedback.created_at }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ feedback.feedback_msg }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ feedback.rate }}</h1>
      </div>
    </div>
    {% endfor %}
    <!-- prettier-ignore -->
    {% endblock content %}

    <!-- //prettier-ignore -->
  </body>
</html>

DiyConnect/main/templates/main/admin_temp/admin_forgot_password.html
{% extends './admin_temp.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Admin | Forgot Passwords</title>
    {% endblock title %}

    <style>
      /*{% block styles %}*/
      .border-admin {
        border: 1px solid black;
        padding: 4px;
      }

      /*{% endblock styles %}*/
    </style>
  </head>

  <body>
    <!-- prettier-ignore -->
    {% block content %}
    <a href="{% url 'main:admin_dashboard' %}" class="button is-info">Home</a>
    <!-- //prettier-ignore -->
    <h1 class="mb-5">This show people who forgot password</h1>

    <div class="columns border-admin is-vcentered">
      <div class="column has-text-centered">
        <h1>Email:</h1>
      </div>
      <div class="column has-text-centered">
        <h1>New Password</h1>
      </div>
      <div class="column has-text-centered">
        <h1>Username:</h1>
      </div>
      <div class="column has-text-centered">
        <h1>created at:</h1>
      </div>
    </div>
    {% for user_data in data %}
    <div class="columns">
      <div class="column has-text-centered">
        <h1>{{ user_data.REFENCE_USER.email }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user_data.new_password_change }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user_data.REFENCE_USER.username }}</h1>
      </div>
      <div class="column has-text-centered">
        <h1>{{ user_data.created_at }}</h1>
      </div>
    </div>
    {% endfor %}
    <!-- prettier-ignore -->
    {% endblock content %}
    <!-- //prettier-ignore -->
  </body>
</html>

DiyConnect/main/templates/main/admin_temp/admin_temp.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title></title>
    {% endblock title %}
    <style>
      .inherit_width {
        width: 100%;
      }
      /* {% block styles %} */
      /* {% endblock styles %} */
    </style>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Hind+Madurai:wght@300;400;500;600;700&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <section class="hero is-fullheight">
      <div class="hero-body">
        <div class="inherit_width">
          <!-- prettier-ignore -->
          {% block content %}
          <!-- //prettier-ignore -->
          <!-- prettier-ignore -->
          {% endblock content %}
          <!-- //prettier-ignore -->
        </div>
      </div>
    </section>

    <script>
      async function initializeCSRF() {
        let response = await fetch("{% url 'main:set_csrf_token' %}", {
          method: "GET",
          credentials: "include", //  Ensures cookies are sent and received
        });

        if (response.ok) {
          console.log("CSRF Token Initialized");
        } else {
          console.error("Failed to initialize CSRF");
        }
      }

      // Call this function when the page loads
      initializeCSRF();
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      // {% block scripts %}
      //{% endblock scripts %}
    </script>
  </body>
</html>