DiyConnect/DiyConnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
urlpatterns = [
    path('admin/', admin.site.urls),
   path("", include("main.urls"))
   
]
handler404  = "main.views.custom_404_view"
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DiyConnect/main/urls.py
from django.urls import path,include

from .  import views

app_name ="main"
urlpatterns = [
    path('', views.index, name="index" ),
    path('authentication_base/', views.authentication_base, name="authentication_base" ),
    path('authentication/login/', views.authentication_login, name="authentication_login" ),
    path('authentication/registration/', views.authentication_registration, name="authentication_registration" ),
    path('authentication/profile/', views.authentication_profile, name="authentication_profile"),
     path('authentication/PreLoad/', views.authentication_preLoad, name="authentication_preLoad"),
          path('authentication/forgot-password/', views.authentication_forgot_password, name="authentication_forgot_password"),
           path('authentication/changepassword/', views.changeNewpassword, name="changeNewpassword"),

     # CRUD OPERATION AUTHENTICATION
    path('authentication/ADD/', views.authentication_ADD, name="authentication_ADD"),
    path('authentication/logout/', views.authentication_logout, name ="authentication_logout"),

    # DIY CONNECT APP
    path('diyconnect/home/', views.home,  name="diyconn_home"),
    
    #People
 path('diyconnect/people/', views.people,  name="people"),
 path('diyconnect/people/friends', views.peopleFriends,  name="peopleFriends"),
 path('diyconnect/people/discover', views.peopleGetDiscover, name ='peopleGetDiscover'),
 path('diyconnect/people/friendRequest', views.peopleFriendRequest_get, name ='peopleFriendRequest_get'),
 path('diyconnect/people/friendRequest/accepted/<int:user_id>', views.peopleFriendRequest_accepted, name ='peopleFriendRequest_accepted'),
  path('diyconnect/people/friendRequest/pending/<int:user_id>', views.peopleFriendRequest_pending, name ='peopleFriendRequest_pending'),
 path('diyconnect/people/add/<int:user_id>', views.peopleAdd, name ='peopleAdd'),
 path('diyconnect/people/delete/<int:user_id>', views.peopleDelete, name ='peopleDelete'),
 
 
    #Search
    path('diyconnect/search/<str:search_item>', views.postSearch,  name="postSearch"),

    #POST
      path('post/getRoleChange/', views.postRoleChange,  name="postRoleChange"),
      path('post/add/', views.postAdd,  name="postAdd"),
            path('post/specific/<int:post_id>', views.postGet_specific,  name="postGet_specific"),   #FINALIZED
      path('post/edit/save/<int:post_id>', views.postEditSave,  name="postEditSave"),
      path('post/edit/<int:post_id>', views.postEdit,  name="postEdit"),
      path('post/get/<int:lastest_post>/<str:role_post>', views.postGet,  name="postGet"),
        path('post/delete/<int:post_id>/', views.postDelete,  name="postGet"),

      path('post/profile/get/<str:username>/', views.postGet_profile, name="postGet_profile"),

      #POST LIKE
       path('post/like/add/', views.postLikeAdd, name="postLikeAdd"),
         path('post/like/removed/', views.postLikeRemoved, name="postLikeRemoved"),

    #Conversations
        path('diyconn/conversation/get/<int:sender_id>', views.MessageConversationGet,  name="MessageConversationGet"),
          path('diyconn/conversation/add/<int:receiver_id>', views.MessageConvesationAdd,  name="MessageConvesationAdd"),
    #Messages
 path('diyconn/messages/mobile', views.MessageMobile,  name="MessageMobile"),
  path('diyconn/messages/mobile/get/<int:user_id>', views.MessageMobileConversationContent,  name="MessageMobileConversationContent"),
  path('diyconn/messages/', views.Messages,  name="Messages"),
  path('diyconn/messages/get', views.MessagesGet,  name="MessagesGet"),
  path('diyconn/messages/add/<int:receiver_id>', views.MessageAdd,  name="MessageAdd"),
  path('diyconn/messages/request/add/<int:receiver_id>', views.MessageAddRequest,  name="MessageAdd"),

  #Profile
    path('diyconn/profile/get/<str:username>/', views.profile_user, name ="profile_user"),
  #Request Task
    path('diyconn/request/fullfiller/cancelled/', views.request_fulfiller_cancelled, name ="request_fulfiller_cancelled"),
       path('diyconn/request/receiver/completed/', views.request_receiver_completed, name ="request_receiver_completed"),

      #INITIALIZED
        path('Initialized/cookies/', views.set_csrf_token,  name="set_csrf_token"),
  
  #Reviews
   path('diyconn/reviews/<int:user_id>', views.reviews,  name="reviews"),


#Notification 
 path('diyconn/notification/', views.notification,  name="notification"),
  path('diyconn/notification/viewed/<int:notif_id>', views.notification_viewed,  name="notification_viewed"),
   #Setting
   path('diyconn/setting/', views.setting,  name="setting"),
    path('diyconn/setting/verify-password', views.setting_verify_password,  name="setting_verify_password"),
     path('diyconn/setting/save-changes', views.setting_save_changes,  name="setting_save_changes"),
 
 #feedback 
    path('diyconn/feedback/add', views.user_feedback,  name="user_feedback"),

 #admin
     path('diyconn/admin-fogotPassword/', views.admin_forgotPassword,  name="admin_forgotPassword"),
     path('diyconn/admin-dashboard/', views.admin_dashboard,  name="admin_dashboard"),
     path('diyconn/admin-checkUserpost/', views.admin_CheckUsers,  name="admin_CheckUsers"),
  path('diyconn/admin-checkUserpostDetails/', views.admin_checkUserpostDetails,  name="admin_checkUserpostDetails"),
    path('diyconn/admin-postDelete/<int:post_id>', views.admin_deletePostDetails,  name="admin_deletePostDetails"),
      path('diyconn/admin-feedback/', views.admin_feedbackCheck,  name="admin_feedbackCheck"),
    path('diyconn/admin-UserDelete/<int:user_id>', views.admin_deleteUser,  name="admin_deleteUser"),


     

]

DiyConnect/main/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
from django.contrib.auth.hashers import check_password
from .models import UserSites, UserPost, UserPost_BLOB, Friendships, UserMessages, MessageStatus,TaskRequest,Review,PostLike,FriendStatus, Notification, NotifyType,NotifyStatus, FogotPasswordFixed,Feedback
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required, user_passes_test
import time
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models.functions import Random
from django.db.models import Q, Max, OuterRef, Subquery, F,Case, When,Exists
from django.db import models
import random
import string

# Create your views here.


#initialized_cookie
@ensure_csrf_cookie
def set_csrf_token(request):
    return JsonResponse({"message": "CSRF token set"})


def index(request):
    context ={}
    return render(request, 'main/index.html', context)



# Authentication
def authentication_base(request):

    context ={}
    return render(request,'main/authentication/auth_base.html',context)

def authentication_login(request):
    if(request.method =="POST"):
        data = json.loads(request.body)    
        try:
            u_check = UserSites.objects.filter(username=data['username']).first()
           
            """
            print("Input Password:", data['password'])
            print("Stored Hashed Password:", u_check.password)
            print(data)
            print(u_check.password)
            print(check_password(data['password'], u_check.password))
            """
            if(check_password(data['password'], u_check.password)):
                user = authenticate(request, username=data['username'], password=data['password'])
                login(request, user)  # Log the user in
                request.session["RolesPostFilter"] = 'Innovator'
                return JsonResponse({"msg": "User has been retrieve", "redirect_url": "/diyconnect/home/"}, status=200)
            else:
                return JsonResponse({"error": "Invalid username or password."}, status=400)
        except:   
             return JsonResponse({"error": "Invalid username or password"}, status=400)
    context ={}
    return render(request,'main/authentication/auth_login.html',context)


def authentication_registration(request):
    context ={}
    return render(request,'main/authentication/auth_registration.html', context)

def authentication_forgot_password(request):
    context={
        
    }
    return render(request,'main/authentication/auth_forgot_pass.html', context)

def authentication_preLoad(request):
    if request.method =="POST":
        data = json.loads(request.body)        
        u_check = UserSites.objects.filter(username = data['username']).exists()
        if(u_check):
            return JsonResponse({"error": "The username has been used."}, status=400)        
        request.session["Pre_User_Profile"] = data
        return JsonResponse({"Profile": "Request Sent", "redirect_url": "/authentication/profile/" }, status=200)    
    return JsonResponse({"error": "Invalid request"}, status=400)
    
def authentication_profile(request):
    user_data = request.session.get("Pre_User_Profile", {})
    context ={
        "UserPreData": user_data
    }
    return render(request,'main/authentication/auth_registrationProfile.html', context)

def authentication_ADD(request):
    if(request.method =="POST"):
        get_image_file = request.FILES.get("ImageFile")
        bio = request.POST.get("bio")
        get_user_data = json.loads(request.POST.get('UserDataPrep'))
        u = UserSites()
        #lastID = UserSites.objects.values('ID').last()
        #u.ID = lastID['ID'] + 1
        u.first_name = get_user_data['firstName']
        u.last_name = get_user_data['lastName']
        u.email = get_user_data['email']
        u.password = get_user_data['password']
        u.profile_picture = get_image_file
        u.city_or_municipality = get_user_data['municipality_or_city']
        u.username = get_user_data['username']
        u.subdivision = get_user_data['subdivision']
        u.bio = bio
        u.save()           
        # Check if data pass server
        """        
        print(get_image_file)
        print(get_user_data)
        print(bio)
        """
        
        return JsonResponse({"msg": "New user created complete."
        ""}, status=200)

    return JsonResponse({"error": "Invalid request"}, status=400)

def authentication_logout(request):
    logout(request)
    return redirect("/authentication/login/")

# DIY CONNECT APP

def home(request):
   
    get_role_post_filter = request.session.get("RolesPostFilter", "Innovator")
    if request.user.is_authenticated:
        get_username = request.user.username
    else:
        get_username = "guest"
    context ={"username": get_username,"role_post_filter":get_role_post_filter}
    return render(request,'main/diyconn/home.html', context)

# POST
@login_required
def postLikeAdd(request):
    if(request.method =="POST"):
        data = json.loads(request.body)
        print(data)
        get_userPost= UserPost.objects.get(ID=data['post_id'])
        p = PostLike()
        p.user =request.user
        p.post = get_userPost
        p.save()
        
       
        
        return JsonResponse({"msg": "Liked Post"}, status=200)
        

@login_required
def postLikeRemoved(request):
    data = json.loads(request.body)
    print(data)
    get_userPost= UserPost.objects.get(ID=data['post_id'])
    get_likePost = PostLike.objects.get(post = get_userPost, user =request.user)
    get_likePost.delete()
    print("removed liked")
    return JsonResponse({"msg": "Liked Post"}, status=200)
def postGet_specific(request,post_id):
     post = UserPost.objects.filter(ID=post_id).first()
     get_post_blobs = UserPost_BLOB.objects.filter(USER_POST_ID=post)
     #print(get_post_blobs)
     if post is None:
         post = False
     context={"post_data":post,
              "post_data_blob":get_post_blobs,
              }
     return render(request,'main/subpages/post/postRetrieve.html', context)


def postGet_profile(request, username):
   
    check_owner_user = False
    user_profile = UserSites.objects.get(username=username)
    user_list_post = UserPost.objects.filter(USER_ID = user_profile).order_by('-modified_at')
    if(request.user==user_profile):
        check_owner_user =True
    context = []
    for post in user_list_post:
            blobs = UserPost_BLOB.objects.filter(USER_POST_ID=post).order_by('position')
            blob_list = [
                {
                    "id": blob.ID,
                    "image_url": blob.blob.url,
                    "position": blob.position
                }
                for blob in blobs
            ]

            context.append({
                "id": post.ID,
                "username":post.USER_ID.username,
                "user_location":{"subdivision": post.USER_ID.subdivision,"city_or_municipality":post.USER_ID.city_or_municipality},
                "title": post.title, 
                "description": post.description,  
                "date_modified": post.modified_at,
                "blobs": blob_list,
                "user_ID":post.USER_ID.ID,
                "check_owner_user":check_owner_user               
            })

    
    
    return JsonResponse({"msg": "Checking if there is a post", "items":context}, status=200)


def postRoleChange(request):
    if(request.method =="POST"):
        data = json.loads(request.body)
        request.session["RolesPostFilter"] = data['role']
      
        return JsonResponse({"msg": "Changing Item Post"}, status=200)


def postGet(request,lastest_post, role_post):
    timeout = 30
    start_time = time.time()
    # = UserPost.objects.filter(user_role_type = role_post )
   
    while time.time() - start_time < timeout:
            try:
                new_posts = UserPost.objects.filter(user_role_type=role_post).order_by("-modified_at")[lastest_post]

                if new_posts:
                    total_likes =0
                    lastest_post +=1  # Update latest post ID
                    get_blob_info  = UserPost_BLOB.objects.filter(USER_POST_ID = new_posts).order_by('position')
                    item = get_blob_info.first().blob.url
                    print(request)
                    get_likes_filter = PostLike.objects.filter(post =new_posts)
                  
                    if request.user.is_authenticated:
                        already_liked = PostLike.objects.filter(post=new_posts, user=request.user).exists()
                       
                    else:
                        already_liked = "guest"
                    for like in get_likes_filter:
                        total_likes+=1
                    return JsonResponse({
                'new_posts':{
                    'id': new_posts.ID,
                    'title': new_posts.title,
                    'description':new_posts.description,
                    'date_modified': new_posts.modified_at,
                    'user': new_posts.USER_ID.ID, 
                    'username': new_posts.USER_ID.username,
                    'user_location':{'subdivision':new_posts.USER_ID.subdivision, 'city_or_municipality': new_posts.USER_ID.city_or_municipality}, 
                    'profile_urls': new_posts.USER_ID.profile_picture.url if new_posts.USER_ID.profile_picture else None,

                    'blob_url': [item.blob.url for item in get_blob_info],
                    "role_post":role_post,
                    "like": total_likes,
                    "already_liked":already_liked,
                   "ownership_post": new_posts.USER_ID == request.user

                  
                    
                    
                },  # Convert queryset to list
                'latest_post_count': lastest_post
            })
         

DiyConnect/main/templates/main/authentication/auth_forgot_pass.html
{% extends './auth_base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- prettier-ignore -->
    {% block title %}
    <!-- //prettier-ignore -->
    <title>Forgot Password | DIY CONNECT</title>
    <!-- prettier-ignore -->
    {% endblock title %}
    <!-- //prettier-ignore -->
    <style>
      /* {% block styles %} */
      .sty-mdl-footer-btn {
        width: 100%;
        display: flex;
        justify-content: center;
      }
      .sty-mdl-head {
        font-size: 36px;
        font-weight: 800;
        color: black;
      }
      .sty-mdl-msg {
        font-size: 20px;
        font-weight: 400;
        color: black;
      }
      .sty-mdl-btn-submit {
        color: #ffffff;
        font-weight: 600;
        background-color: #283618;
        font-size: 25px;
      }

      @media (max-width: 768px) {
        .sty-mdl-head {
          font-size: 24px;
        }
      }
      /* {% endblock styles %}*/
    </style>
  </head>
  <body>
    <!-- prettier-ignore -->
    {% block content %}
    <!-- //prettier-ignore -->
    <div class="container container-bkg">
      <div class="has-text-centered">
        <h1 class="sty-sty-auth-header sty-size-auth-header mb-6">
          DIY Connect
        </h1>
        <h1 class="sty-sty-sub-header-authLogin mb-4 sty-size-sub-header">
          Change Password
        </h1>
        <div>
          <div class="columns">
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
            <div class="column sty-sty-auth-label-mobile">
              <div class="has-text-centered">
                <h1 class="sty-sty-auth-label sty-size-auth-label">Email:</h1>
              </div>
            </div>
            <div class="column is-4">
              <div>
                <input
                  type="email"
                  class="input is-medium sty-sty-inp-border"
                  placeholder="Email"
                  id="inp_email"
                />
              </div>
            </div>
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
          </div>

          <div>
            <h1 class="sty-err-msg" id="err_msg">
              We could not find an account associated with that email address.
            </h1>
            <div
              class="button sty-btn-submit"
              id="btn_submit"
              onclick="btn_submit_forgotPassword()"
            >
              Submit
            </div>
          </div>
          <h1 class="sty-sty-subtitle-login mb-5">
            Please enter the email address associated with your username. Our
            support team will assist you in resetting your password. Pleased be
            advice that it will take time to received an email
          </h1>
        </div>
      </div>
    </div>
    <!-- MODAL-->
    <div class="modal" id="mdl_changePassword">
      <div class="modal-background" onclick=""></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title sty-mdl-head has-text-centered">
            Complete Forgot Password
          </p>
        </header>
        <section class="modal-card-body has-text-centered">
          <h1 class="sty-mdl-msg">
            Your password has been successfully changed. Please wait for an
            email with your new password.
          </h1>
        </section>

        <footer class="modal-card-foot">
          <div class="sty-mdl-footer-btn">
            <a
              class="button sty-mdl-btn-submit"
              href="{% url 'main:authentication_login' %}"
              onclick=""
            >
              Continue
            </a>
          </div>
        </footer>
      </div>
    </div>
    <!-- MODAL -->
    <!-- prettier-ignore -->
    {% endblock content %}
    <!-- //prettier-ignore -->

    <script>
      // {% block scripts %}
      let mdl_changePassword = document.getElementById("mdl_changePassword");

      let err_msg = document.getElementById("err_msg");
      err_msg.style.display = "None";
      function btn_submit_forgotPassword() {
        mdl_changePassword.classList.remove("is-active");
        err_msg.style.display = "None";
        let inp_email = document.getElementById("inp_email");

        let json_data = {
          user_email: inp_email.value,
        };
        let response = fetch("{% url 'main:changeNewpassword' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": getCookie("csrftoken"),
          },
          mode: "same-origin",
          body: JSON.stringify(json_data),
        })
          .then((response) => {
            if (!response.ok) {
              // If response status is not OK (400, 500, etc.), throw an error
              return response.json().then((errData) => {
                throw errData;
              });
            }
            return response.json(); // Otherwise, parse the JSON response
          })
          .then((msg) => {
            mdl_changePassword.classList.add("is-active");
            console.log(msg);
          })
          .catch((err) => {
            //console.log(err);
            err_msg.style.display = "block";
            console.log("Error:", err.error || "An unexpected error occurred");
          });
      }
      // {% endblock scripts %}
    </script>
  </body>
</html>

DiyConnect/main/templates/main/authentication/auth_login.html
{% extends './auth_base.html' %}

<html>
  <head>
    <!-- prettier-ignore -->
    {% block title %}
    <!-- //prettier-ignore -->
    <title>Login | DIY CONNECT</title>
    <!-- prettier-ignore -->
    {% endblock title %}
    <!-- //prettier-ignore
      -->
  </head>

  <body>
    {% load static %}

    <!-- prettier-ignore -->
    {% block content %}
    <!-- //prettier-ignore -->
    <div class="container container-bkg">
      <div class="has-text-centered">
        <h1 class="sty-sty-auth-header sty-size-auth-header">DIY Connect</h1>
        <img
          class="image_logo mb-6"
          src="{% static 'main/images/diy_conn_logo_bkg.png' %}"
          alt="My image"
        />

        <h1 class="sty-sty-sub-header-authLogin mb-4 sty-size-sub-header">
          Login
        </h1>
        <div>
          <div class="columns">
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
            <div class="column sty-sty-auth-label-mobile">
              <div class="has-text-centered">
                <h1 class="sty-sty-auth-label sty-size-auth-label">
                  Username:
                </h1>
              </div>
            </div>
            <div class="column is-4">
              <div>
                <input
                  type="text"
                  class="input is-medium sty-sty-inp-border"
                  placeholder="Username"
                  id="inp_username"
                />
              </div>
            </div>
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
          </div>
          <div class="columns">
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
            <div class="column sty-sty-auth-label-mobile">
              <div class="has-text-centered">
                <h1 class="sty-sty-auth-label sty-size-auth-label">
                  Password:
                </h1>
              </div>
            </div>
            <div class="column is-4">
              <div>
                <input
                  type="password"
                  class="input is-medium sty-sty-inp-border"
                  placeholder="Password"
                  id="inp_password"
                />
              </div>
            </div>
            <div class="column is-2 sty-sty-auth-label-mobile"></div>
          </div>

          <div>
            <h1 class="sty-sty-subtitle-login mb-5">
              Don't you have an account??
              <a href="{% url 'main:authentication_registration'%}"
                >Register Here</a
              >
            </h1>

            <h1 class="sty-err-msg" id="err_msg"></h1>
            <div class="button sty-btn-submit" id="btn_submit">Submit</div>

            <h1 class="sty-sty-subtitle-login mb-5">
              Or just visit the site to see what offers waiting for you
              <a href="/diyconnect/home/">Proceed as a guest</a>
            </h1>
            <a
              href="{% url 'main:authentication_forgot_password' %}"
              class="has-text-centered"
              >Forgot password?
            </a>
            <br />
            <br />
            <a
              href="{% static 'main/pdf_files/UserManual-DIY_CONNECT_PLATFORM.pdf' %}"
              class="has-text-centered"
              ><u>Check User Manual</u></a
            >
          </div>
        </div>
      </div>
    </div>

    <!-- prettier-ignore -->
    {% endblock content %}
    <!-- //prettier-ignore -->
  </body>
  <script>
    //{% block scripts %}
    let btn_submit = document.getElementById("btn_submit");
    let err_msg = document.getElementById("err_msg");
    btn_submit.addEventListener("click", () => {
      err_msg.textContent = ``;
      let json_data = Validate();
      let response = fetch("{% url 'main:authentication_login' %}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": getCookie("csrftoken"),
        },
        mode: "same-origin",
        body: JSON.stringify(json_data),
      })
        .then((response) => {
          if (!response.ok) {
            // If response status is not OK (400, 500, etc.), throw an error
            return response.json().then((errData) => {
              throw errData;
            });
          }
          return response.json(); // Otherwise, parse the JSON response
        })
        .then((msg) => {
          console.log(msg);
          window.location.href = msg.redirect_url;
        })
        .catch((err) => {
          //console.log(err);
          console.log("Error:", err.error || "An unexpected error occurred");

          err_msg.textContent = `${err.error}`;
        });
    });
    function Validate() {
      //Given

      let inp_username = document.getElementById("inp_username").value;
      let inp_password = document.getElementById("inp_password").value;

      data = {
        username: inp_username,
        password: inp_password,
      };
      return data;
    }

    //{% endblock scripts %}
  </script>
</html>